/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/guest/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GuestApi_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guest/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GuestApi_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guest/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GuestApi_listAvailableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/bookings/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OwnerApi_listUpcomingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OwnerApi_listEventTypes"];
        put?: never;
        post: operations["OwnerApi_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["OwnerApi_deleteEventType"];
        options?: never;
        head?: never;
        patch: operations["OwnerApi_updateEventType"];
        trace?: never;
    };
    "/api/owner/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OwnerApi_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            details?: string;
        };
        Booking: {
            id: string;
            eventTypeId: string;
            eventTypeTitle: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            guest: components["schemas"]["GuestContact"];
            /** Format: date-time */
            createdAt: string;
        };
        BookingListResponse: {
            items: components["schemas"]["Booking"][];
            /** Format: int32 */
            total: number;
        };
        CreateBookingRequest: {
            eventTypeId: string;
            /** Format: date-time */
            startAt: string;
            guest: components["schemas"]["GuestContact"];
        };
        CreateEventTypeRequest: {
            title: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        DeleteEventTypeResponse: {
            id: string;
        };
        EventType: {
            id: string;
            title: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        EventTypeListResponse: {
            items: components["schemas"]["EventType"][];
            /** Format: int32 */
            total: number;
        };
        GuestContact: {
            name: string;
            email: string;
            note?: string;
        };
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
        } & WithRequired<components["schemas"]["ApiError"], "code">;
        OutOfWindowError: {
            /** @enum {string} */
            code: "BOOKING_WINDOW_EXCEEDED";
        } & WithRequired<components["schemas"]["ApiError"], "code">;
        OwnerProfile: {
            id: string;
            displayName: string;
            email: string;
        };
        Slot: {
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            isAvailable: boolean;
            /** @enum {string} */
            busyReason?: "BOOKING" | "OWNER_BLOCK";
        };
        /**
         * @description Conflict means the requested interval overlaps with any owner busy interval
         *     (including existing bookings and owner-defined blocks), regardless of event type.
         */
        SlotConflictError: {
            /** @enum {string} */
            code: "SLOT_ALREADY_BOOKED";
        } & WithRequired<components["schemas"]["ApiError"], "code">;
        /**
         * @example {
         *       "eventTypeId": "event-15",
         *       "windowDays": 14,
         *       "date": "2026-04-23",
         *       "timezone": "Europe/Moscow",
         *       "workdayStart": "09:00",
         *       "workdayEnd": "18:00",
         *       "slotDurationMinutes": 15,
         *       "items": [
         *         {
         *           "startAt": "2026-04-23T06:00:00Z",
         *           "endAt": "2026-04-23T06:15:00Z",
         *           "isAvailable": true
         *         },
         *         {
         *           "startAt": "2026-04-23T06:15:00Z",
         *           "endAt": "2026-04-23T06:30:00Z",
         *           "isAvailable": false,
         *           "busyReason": "BOOKING"
         *         },
         *         {
         *           "startAt": "2026-04-23T06:30:00Z",
         *           "endAt": "2026-04-23T06:45:00Z",
         *           "isAvailable": true
         *         },
         *         {
         *           "startAt": "2026-04-23T06:45:00Z",
         *           "endAt": "2026-04-23T07:00:00Z",
         *           "isAvailable": false,
         *           "busyReason": "OWNER_BLOCK"
         *         }
         *       ]
         *     }
         */
        SlotListResponse: {
            eventTypeId: string;
            /** Format: int32 */
            windowDays: number;
            /** Format: date */
            date: string;
            timezone: string;
            workdayStart: string;
            workdayEnd: string;
            /** Format: int32 */
            slotDurationMinutes: number;
            items: components["schemas"]["Slot"][];
        };
        UpdateEventTypeRequest: {
            title?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        ValidationError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR";
        } & WithRequired<components["schemas"]["ApiError"], "code">;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GuestApi_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"] | components["schemas"]["ValidationError"] | components["schemas"]["NotFoundError"] | components["schemas"]["OutOfWindowError"] | components["schemas"]["SlotConflictError"];
                };
            };
        };
    };
    GuestApi_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeListResponse"];
                };
            };
        };
    };
    GuestApi_listAvailableSlots: {
        parameters: {
            query: {
                date: string;
                windowDays?: number;
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotListResponse"] | components["schemas"]["ValidationError"] | components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerApi_listUpcomingBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingListResponse"];
                };
            };
        };
    };
    OwnerApi_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeListResponse"];
                };
            };
        };
    };
    OwnerApi_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"] | components["schemas"]["ValidationError"];
                };
            };
        };
    };
    OwnerApi_deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteEventTypeResponse"] | components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerApi_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"] | components["schemas"]["ValidationError"] | components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerApi_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerProfile"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
